name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
      - name: Build
        run: go install github.com/mfridman/tparse@main
      - name: Run tests with GITHUB_STEP_SUMMARY
        shell: bash
        # Note the use of  || true. This so the job doesn't fail at that line. We want to preserve -follow
        # as part of the test output, but not output it to the summary page, which is done in the proceeding
        # command when we parse the output.jsonl file.
        run: |
          go test -v -count=1 -race -json -cover ./...  | tee output.jsonl | tparse -notests -follow -all -trimpath=auto || true
          tparse -format markdown -file output.jsonl -all -trimpath=auto > $GITHUB_STEP_SUMMARY
